on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
        
      - name: Install node dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 172.84.132.178
          username: admin
          password: Ek7XbbONRScU7o8
          protocol: ftp
          port: 21
          server-dir: /public_html/
          local-dir: ./dist/
          
      - name: Delete dist folder
        run: rm -rf ./dist
